import localFont from "next/font/local";
import "./globals.css";
import Footer from "./component/Footer";
import Navbar from "./component/navbar";
import Sessionwrapper from "./component/Sessionwrapper";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Sessionwrapper>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
              <Navbar/>

        {children}
        <Footer/>
      </body>
    </html>
    </Sessionwrapper>
  );
}
